//! Direct port of Taffy's `compute/grid/explicit_grid.rs`.
//!
//! Helper functions for initialising `GridTrack`s from styles. This mainly
//! consists of evaluating the explicit grid template (including `repeat()`)
//! and creating implicit tracks from `grid-auto-rows`/`grid-auto-columns`.

const std = @import("std");
const geometry = @import("../../geometry.zig");
const style = @import("../../style/mod.zig");
const grid_style = @import("../../style/grid.zig");
const math = @import("../../util/math.zig");
const grid_track = @import("types/grid_track.zig");
const counts_mod = @import("types/grid_track_counts.zig");

const GridTrack = grid_track.GridTrack;
const TrackCounts = counts_mod.TrackCounts;

/// The maximum number of tracks in each direction from the start of the explicit grid
pub const MAX_GRID_TRACKS: u16 = 10_000;

/// The auto-repeat fit strategy to use
pub const AutoRepeatStrategy = enum {
    /// If the grid container has a definite size or max size in the relevant axis:
    /// the number of repetitions is the largest possible positive integer that
    /// does not cause the grid to overflow the content box of its grid container.
    max_repetitions_that_do_not_overflow,
    /// Otherwise, if the grid container has a definite min size in the relevant
    /// axis: the number of repetitions is the smallest possible positive integer
    /// that fulfills that minimum requirement.
    min_repetitions_that_do_overflow,
};

pub const ExplicitGridSize = struct {
    /// The number of `auto-fill`/`auto-fit` repetitions
    auto_repetitions: u16 = 0,
    /// The number of tracks in the explicit grid template
    track_count: u16 = 0,
};

/// ...treating each track as its max track sizing function if that is definite or
/// as its minimum track sizing function otherwise, flooring the max track sizing
/// function by the min track sizing function if both are definite
fn track_definite_value(sizing_function: grid_style.TrackSizingFunction, parent_size: ?f32) f32 {
    const max_size = sizing_function.max.definite_value(parent_size);
    const min_size = sizing_function.min.definite_value(parent_size);
    if (max_size) |maximum| return math.f32_maybe_max(maximum, min_size);
    return min_size orelse 0;
}

/// Compute the number of rows and columns in the explicit grid
pub fn compute_explicit_grid_size_in_axis(
    item_style: *const style.Style,
    auto_fit_container_size: ?f32,
    auto_fit_strategy: AutoRepeatStrategy,
    axis: geometry.AbsoluteAxis,
) ExplicitGridSize {
    const template: []const grid_style.GridTemplateComponent = if (axis == .horizontal) item_style.grid_template_columns else item_style.grid_template_rows;

    // If template contains no tracks, then there are trivially zero explicit tracks
    if (template.len == 0) return .{};

    // If there are any repetitions that contain no tracks, then the whole definition
    // should be considered invalid and we default to no explicit tracks
    for (template) |track_def| {
        if (track_def == .repeat and track_def.repeat.track_count() == 0) return .{};
    }

    // Compute the number of tracks generated by single track definitions and
    // repetitions with a fixed repetition count (clamping to the maximum track limit)
    var non_auto_repeating_track_count: u32 = 0;
    for (template) |track_def| {
        const additional_tracks: u32 = switch (track_def) {
            .single => 1,
            .repeat => |repeat| switch (repeat.count) {
                .count => |count| @as(u32, count) * @as(u32, repeat.track_count()),
                .auto_fit, .auto_fill => 0,
            },
        };
        non_auto_repeating_track_count = @min(non_auto_repeating_track_count +| additional_tracks, MAX_GRID_TRACKS);
    }

    var auto_repetition_count: u16 = 0;
    for (template) |track_def| {
        if (is_auto_repetition(track_def)) auto_repetition_count += 1;
    }
    var all_track_defs_have_fixed_component = true;
    for (template) |track_def| {
        switch (track_def) {
            .single => |sizing_function| {
                if (!sizing_function.has_fixed_component()) all_track_defs_have_fixed_component = false;
            },
            .repeat => |repeat| {
                for (repeat.tracks) |sizing_function| {
                    if (!sizing_function.has_fixed_component()) all_track_defs_have_fixed_component = false;
                }
            },
        }
    }

    const template_is_valid = auto_repetition_count == 0 or (auto_repetition_count == 1 and all_track_defs_have_fixed_component);

    // If the template is invalid, disregard it entirely and default to zero explicit tracks
    if (!template_is_valid) return .{};

    // If there are no auto repetitions, the number of explicit tracks is simply the
    // length of the track definition vector.
    if (auto_repetition_count == 0) return .{ .track_count = @intCast(non_auto_repeating_track_count) };

    // Find the auto repetition and the insertion point of its repetitions
    var auto_repeat_insertion_point: u32 = 0;
    var repetition_definition: grid_style.GridTemplateRepetition = undefined;
    for (template) |track_def| {
        switch (track_def) {
            .single => auto_repeat_insertion_point +|= 1,
            .repeat => |repeat| switch (repeat.count) {
                .count => |count| auto_repeat_insertion_point +|= @as(u32, count) * @as(u32, repeat.track_count()),
                .auto_fit, .auto_fill => {
                    repetition_definition = repeat;
                    break;
                },
            },
        }
        if (is_auto_repetition(track_def)) break;
    }
    const repetition_track_count: u16 = repetition_definition.track_count();

    // Determine the number of repetitions
    var num_repetitions: u32 = 1;
    if (auto_fit_container_size) |inner_container_size| {
        const parent_size: ?f32 = inner_container_size;

        var non_repeating_track_used_space: f32 = 0;
        for (template) |track_def| {
            switch (track_def) {
                .single => |sizing_function| {
                    non_repeating_track_used_space += track_definite_value(sizing_function, parent_size);
                },
                .repeat => |repeat| switch (repeat.count) {
                    .count => |count| {
                        var sum: f32 = 0;
                        for (repeat.tracks) |sizing_function| sum += track_definite_value(sizing_function, parent_size);
                        non_repeating_track_used_space += sum * @as(f32, @floatFromInt(count));
                    },
                    .auto_fit, .auto_fill => {},
                },
            }
        }
        const gap_size = (if (axis == .horizontal) item_style.gap.width else item_style.gap.height).resolve(inner_container_size);

        // Compute the amount of space that a single repetition of the repeated track list takes
        var per_repetition_track_used_space: f32 = 0;
        for (repetition_definition.tracks) |sizing_function| {
            per_repetition_track_used_space += track_definite_value(sizing_function, parent_size);
        }

        // We special case the first repetition because the number of gaps in the first
        // repetition depends on the number of non-repeating tracks in the template
        const first_repetition_and_non_repeating_tracks_used_space = non_repeating_track_used_space +
            per_repetition_track_used_space +
            (@as(f32, @floatFromInt((non_auto_repeating_track_count + repetition_track_count) -| 1))) * gap_size;

        if (first_repetition_and_non_repeating_tracks_used_space > inner_container_size) {
            num_repetitions = 1;
        } else {
            const per_repetition_gap_used_space = @as(f32, @floatFromInt(repetition_track_count)) * gap_size;
            const per_repetition_used_space = per_repetition_track_used_space + per_repetition_gap_used_space;
            const num_repetition_that_fit = (inner_container_size - first_repetition_and_non_repeating_tracks_used_space) / per_repetition_used_space;

            num_repetitions = switch (auto_fit_strategy) {
                .max_repetitions_that_do_not_overflow => saturating_f32_to_u32(@floor(num_repetition_that_fit)) +| 1,
                .min_repetitions_that_do_overflow => saturating_f32_to_u32(@ceil(num_repetition_that_fit)) +| 1,
            };
        }
    }

    // Clamp the number of repetitions based on the auto-repeat's insertion point
    const remaining_tracks: u32 = @as(u32, MAX_GRID_TRACKS) -| auto_repeat_insertion_point;
    const rep_count_u32: u32 = repetition_track_count;
    const final_repetitions: u16 = if (remaining_tracks == 0) 0 else blk: {
        const max_repetitions = (remaining_tracks + rep_count_u32 - 1) / rep_count_u32;
        break :blk @intCast(std.math.clamp(num_repetitions, 1, max_repetitions));
    };

    const grid_template_track_count: u16 = @intCast(@min(
        @as(u32, non_auto_repeating_track_count) + @as(u32, repetition_track_count) * final_repetitions,
        MAX_GRID_TRACKS,
    ));
    return .{ .auto_repetitions = final_repetitions, .track_count = grid_template_track_count };
}

fn saturating_f32_to_u32(value: f32) u32 {
    if (value <= 0) return 0;
    if (value >= 4_294_967_295.0) return std.math.maxInt(u32);
    return @intFromFloat(value);
}

fn is_auto_repetition(value: grid_style.GridTemplateComponent) bool {
    return value == .repeat and (value.repeat.count == .auto_fit or value.repeat.count == .auto_fill);
}

/// Callback used to query whether a track has items placed in it (used to
/// collapse empty `auto-fit` tracks). Receives the opaque context and the
/// sparse track index.
pub const TrackHasItemsFn = *const fn (context: ?*const anyopaque, index: usize) bool;

/// Resolve the track sizing functions of explicit tracks, automatically created
/// tracks, and gutters given a set of track counts and the relevant styles.
pub fn initialize_grid_tracks(
    tracks: *std.ArrayList(GridTrack),
    allocator: std.mem.Allocator,
    counts: TrackCounts,
    item_style: *const style.Style,
    axis: geometry.AbsoluteAxis,
    auto_repetition_count: u16,
    track_has_items_context: ?*const anyopaque,
    track_has_items: TrackHasItemsFn,
) !void {
    const track_template: []const grid_style.GridTemplateComponent = if (axis == .horizontal) item_style.grid_template_columns else item_style.grid_template_rows;
    const auto_tracks: []const grid_style.TrackSizingFunction = if (axis == .horizontal) item_style.grid_auto_columns else item_style.grid_auto_rows;
    const gap = if (axis == .horizontal) item_style.gap.width else item_style.gap.height;

    tracks.clearRetainingCapacity();
    try tracks.append(allocator, GridTrack.gutter(gap));

    const auto_track_count = auto_tracks.len;

    // Create negative implicit tracks
    if (counts.negative_implicit > 0) {
        if (auto_track_count == 0) {
            try create_implicit_tracks(tracks, allocator, counts.negative_implicit, null, 0, gap);
        } else {
            const offset = auto_track_count - (@as(usize, counts.negative_implicit) % auto_track_count);
            try create_implicit_tracks(tracks, allocator, counts.negative_implicit, auto_tracks, offset, gap);
        }
    }

    var current_track_index: usize = counts.negative_implicit;

    // The maximum index up to which explicit tracks may be created
    const explicit_track_limit: usize = @as(usize, counts.negative_implicit) + counts.explicit;

    // Create explicit tracks
    if (counts.explicit > 0 and track_template.len > 0) {
        for (track_template) |track_def| {
            switch (track_def) {
                .single => |sizing_function| {
                    if (current_track_index < explicit_track_limit) {
                        try tracks.append(allocator, GridTrack.new(sizing_function.min_sizing_function(), sizing_function.max_sizing_function()));
                        try tracks.append(allocator, GridTrack.gutter(gap));
                        current_track_index += 1;
                    }
                },
                .repeat => |repeat| switch (repeat.count) {
                    .count => |count| {
                        const repeated_track_count = @min(@as(usize, repeat.track_count()) * @as(usize, count), explicit_track_limit - current_track_index);
                        var index: usize = 0;
                        while (index < repeated_track_count) : (index += 1) {
                            const sizing_function = repeat.tracks[index % repeat.tracks.len];
                            try tracks.append(allocator, GridTrack.new(sizing_function.min_sizing_function(), sizing_function.max_sizing_function()));
                            try tracks.append(allocator, GridTrack.gutter(gap));
                            current_track_index += 1;
                        }
                    },
                    .auto_fit, .auto_fill => {
                        const auto_repeated_track_count = @min(@as(usize, repeat.track_count()) * @as(usize, auto_repetition_count), explicit_track_limit - current_track_index);
                        var index: usize = 0;
                        while (index < auto_repeated_track_count) : (index += 1) {
                            const repeated_sizing_function = repeat.tracks[index % repeat.tracks.len];
                            var track = GridTrack.new(repeated_sizing_function.min_sizing_function(), repeated_sizing_function.max_sizing_function());
                            var gutter = GridTrack.gutter(gap);

                            // Auto-fit tracks that don't contain items should be collapsed.
                            if (repeat.count == .auto_fit and !track_has_items(track_has_items_context, current_track_index)) {
                                track.collapse();
                                gutter.collapse();
                            }

                            try tracks.append(allocator, track);
                            try tracks.append(allocator, gutter);
                            current_track_index += 1;
                        }

                        // Is this auto-repeat at the very end of the track list?
                        const is_last = current_track_index == counts.len();

                        // If the auto-fit repeat is at the very end of the track list, then
                        // there will be no non-collapsed track after it; iterate backwards
                        // collapsing tracks and gutters until we find the first non-collapsed track.
                        if (repeat.count == .auto_fit and is_last) {
                            var i = tracks.items.len;
                            while (i > 0) {
                                i -= 1;
                                const previous_track = &tracks.items[i];
                                if (previous_track.kind == .track and !previous_track.is_collapsed) break;
                                previous_track.collapse();
                            }
                        }
                    },
                },
            }
        }
    }

    const grid_area_tracks: usize = (@as(usize, counts.negative_implicit) + counts.explicit) - current_track_index;

    // Create positive implicit tracks
    const positive_count: usize = counts.positive_implicit + grid_area_tracks;
    if (auto_track_count == 0) {
        try create_implicit_tracks(tracks, allocator, positive_count, null, 0, gap);
    } else {
        try create_implicit_tracks(tracks, allocator, positive_count, auto_tracks, 0, gap);
    }

    // Mark first and last grid lines as collapsed
    if (tracks.items.len > 0) {
        tracks.items[0].collapse();
        tracks.items[tracks.items.len - 1].collapse();
    }
}

/// Utility function for repeating logic of creating implicit tracks. When
/// `auto_tracks` is null, AUTO tracks are generated.
fn create_implicit_tracks(
    tracks: *std.ArrayList(GridTrack),
    allocator: std.mem.Allocator,
    count: usize,
    auto_tracks: ?[]const grid_style.TrackSizingFunction,
    offset: usize,
    gap: style.dimension.LengthPercentage,
) !void {
    var index: usize = 0;
    while (index < count) : (index += 1) {
        const track_def: grid_style.TrackSizingFunction = if (auto_tracks) |defined|
            defined[(offset + index) % defined.len]
        else
            .auto;
        try tracks.append(allocator, GridTrack.new(track_def.min_sizing_function(), track_def.max_sizing_function()));
        try tracks.append(allocator, GridTrack.gutter(gap));
    }
}

test "explicit grid auto-fill repetitions respect gaps" {
    const testing = @import("std").testing;
    const columns = [_]grid_style.GridTemplateComponent{.{ .repeat = .{
        .count = .auto_fill,
        .tracks = &[_]grid_style.TrackSizingFunction{grid_style.TrackSizingFunction.from_length(40)},
    } }};
    const rows = [_]grid_style.GridTemplateComponent{.{ .repeat = .{
        .count = .auto_fill,
        .tracks = &[_]grid_style.TrackSizingFunction{grid_style.TrackSizingFunction.from_length(20)},
    } }};
    const item_style = style.Style{
        .display = .grid,
        .grid_template_columns = &columns,
        .grid_template_rows = &rows,
        .size = .{ .width = .length(140), .height = .length(100) },
        .gap = .{ .width = .length(20), .height = .length(20) },
    };
    // width 140: 2 tracks + 1 gap (Rust `explicit_grid_sizing_auto_fill_gap`)
    const horizontal = compute_explicit_grid_size_in_axis(&item_style, 140, .max_repetitions_that_do_not_overflow, .horizontal);
    try testing.expectEqual(@as(u16, 2), horizontal.track_count);
    try testing.expectEqual(@as(u16, 2), horizontal.auto_repetitions);
    // height 100: 3 tracks + 2 gaps
    const vertical = compute_explicit_grid_size_in_axis(&item_style, 100, .max_repetitions_that_do_not_overflow, .vertical);
    try testing.expectEqual(@as(u16, 3), vertical.track_count);
    try testing.expectEqual(@as(u16, 3), vertical.auto_repetitions);
}

test "invalid templates with zero-track repetitions are ignored" {
    const testing = @import("std").testing;
    const columns = [_]grid_style.GridTemplateComponent{.{ .repeat = .{
        .count = .{ .count = 2 },
        .tracks = &[_]grid_style.TrackSizingFunction{},
    } }};
    const item_style = style.Style{ .display = .grid, .grid_template_columns = &columns };
    const horizontal = compute_explicit_grid_size_in_axis(&item_style, 200, .max_repetitions_that_do_not_overflow, .horizontal);
    try testing.expectEqual(@as(u16, 0), horizontal.track_count);
}
